import datetime
pepe = input("Ingresa tu nombre -- > ")
pepoide = input ("Ingresa tu apellido -- >")
alo= input ("Ingresa tu edad -- > ")
salamaleco = input("Pais donde vives --> ")
sala = input("Ciudad donde vives -- > ")
print("Resultados:")
print("Nombre: "+pepe)
print("Apellido: "+pepoide)
print("Edad: "+alo)
print("Pais: "+salamaleco)
print("Ciudad: "+sala)
print("Registrado el:",datetime.datetime.now())